# Generated by Django 4.2 on 2023-04-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.TextField(verbose_name='Иконка сайта')),
                ('url', models.TextField(verbose_name='URL сайта')),
                ('email', models.TextField(verbose_name='Email')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
            ],
        ),
    ]
