# Generated by Django 4.2 on 2023-04-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_infocard_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infocard',
            options={'verbose_name': 'Карточка с паролем', 'verbose_name_plural': 'Карточки с паролем'},
        ),
        migrations.AddField(
            model_name='infocard',
            name='blue',
            field=models.IntegerField(default=12, verbose_name='Синий цвет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infocard',
            name='green',
            field=models.IntegerField(default=12, verbose_name='Зеленый цвет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infocard',
            name='red',
            field=models.IntegerField(default=12, verbose_name='Красный цвет'),
            preserve_default=False,
        ),
    ]
