# Generated by Django 4.2 on 2023-04-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_infocard_options_infocard_blue_infocard_green_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocard',
            name='name_of_service',
            field=models.CharField(default=1312, max_length=100, verbose_name='Имя сервиса'),
            preserve_default=False,
        ),
    ]
